repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'v2.7.1'
    hooks:
      - id: prettier
        args: ['src/']
        additional_dependencies:
          - 'prettier@^2.7.1'
          - '@trivago/prettier-plugin-sort-imports@^4.0.0'
